### ISSUE TITLE
Booting IceLake server with EDK2 BIOS

### ISSUE THREAD

**Issue by jdhanasekar** [intel/FSP#66]
Hi Intel FSP Team,

I am having Ice Lake based server. I want to boot my server platform with EDK2 BIOS.  
Is it possible to boot the Ice Lake based server with this ```IceLakeBinPkg```  in EDK2 source code?

**Comment by nate-desimone** [comment]
Hi @jdhanasekar, the `IcelakeFspBinPkg` is for the client version of Ice Lake, not the server one. We are working on releasing a `WhitleyFspBinPkg` along with a `WhitleyOpenBoardPkg` on [edk2-platforms](https://github.com/tianocore/edk2-platforms/tree/master/Platform/Intel) that will follow the [MinPlatform Architecture](https://tianocore-docs.github.io/edk2-MinimumPlatformSpecification/draft/) and boot Ice Lake based servers.

**Comment by jdhanasekar** [comment]
Hi @nate-desimone, Thanks for the info. I am having ```coyote pass server``` and will ``WhitleyOpenBoardPkg`` support coyote pass server platform or I have to port platform changes accordingly?

**Comment by pietrushnic** [comment]
@nate-desimone is there any way to obtain FSP release roadmap?

**Comment by nate-desimone** [comment]
@jdhanasekar Our initial release will support Wilson City. We didn't any explicit plans to add support for Coyote Pass but it would not be very difficult to do so. If you are interested in helping with that effort after we get `WhitleyOpenBoardPkg` that would be very appreciated.

@pietrushnic, we do not have a roadmap.

**Comment by jdhanasekar** [comment]
@jdhanasekar . I am interested in helping to port changes for ``coyote pass`` in ``WhitleyOpenBoardPkg`` once it is released.
Please inform me once WhitleyOpenBoardPkg is released.

**Comment by paulmenzel** [comment]
Why did you close the issue? Has WhitleyFspBinPkg been released?

**Comment by jdhanasekar** [comment]
WhitelyFspBinPkg is not release yet.  I thought I got the required info. So, I am closed the issue.  Do You want me to keep the issue open till they release WhitelyFspBinPkg for  Wilson City CRB ?
