### ISSUE TITLE
How to configure Vbt.bin via Vbt.json on TigerLake platform?

### ISSUE THREAD

**Issue by seattlezhu** [intel/FSP#67]
Are there any tool to configure Vbt.bin within Vbt.json on TigerLake platrom? Like BMP.exe which could configure Vbt.bin with Vbt.bsf file on other platform.

**Comment by swong23** [comment]
BPM tool was slowly phased out... Contact your Intel Graphics representative for the new DisCon tool to understand its capability.

**Comment by seattlezhu** [comment]
Ok, got it, thanks!
