### ISSUE TITLE
Rocket Lake FSP support

### ISSUE THREAD

**Issue by 6d6178667269747a** [intel/FSP#84]
Are there any plans to publish the FSP binaries and headers for the Rocket Lake platform (h500 series, 11th core series desktop)?

**Comment by felixsinger** [comment]
I would be interested too

**Comment by nate-desimone** [comment]
Any update here?

**Comment by felixsinger** [comment]
@nate-desimone It's not useful for me, but thanks for asking though! The issue can be closed in my opinion.

**Comment by nate-desimone** [comment]
Sounds good, closing.
