### ISSUE TITLE
error: ‘FspPcdListLibNull’ defined but not used

### ISSUE THREAD

**Issue by rockleesan** [intel/FSP#89]
`src/FSP/WhitleyFspBinPkg/Library/FspPcdListLibNull/FspPcdListLibNull.c:13:1: error: ‘FspPcdListLibNull’ defined but not used [-Werror=unused-function]
   13 | FspPcdListLibNull (
      | ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors`

Trying to compile **WilsonCityRvp**, got an error of unused function, fixed by:

```diff --git a/WhitleyFspBinPkg/Library/FspPcdListLibNull/FspPcdListLibNull.c b/WhitleyFspBinPkg/Library/FspPcdListLibNull/FspPcdListLibNull.c
index a4d89f8..d1b8699 100644
--- a/WhitleyFspBinPkg/Library/FspPcdListLibNull/FspPcdListLibNull.c
+++ b/WhitleyFspBinPkg/Library/FspPcdListLibNull/FspPcdListLibNull.c
@@ -8,11 +8,11 @@
   SPDX-License-Identifier: BSD-2-Clause-Patent
 **/

-STATIC
+/*STATIC
 VOID
 FspPcdListLibNull (
   VOID
   )
 {

-}
+}*/```

**Comment by nate-desimone** [comment]
Fixed in `8beacd5`.
