### ISSUE TITLE
ElkhartLake MR5 VBT BSF file is not correct 

### ISSUE THREAD

**Issue by belotv** [intel/FSP#90]
Hi @swong23,

The BSF provided in https://github.com/intel/FSP/tree/master/ElkhartLakeFspBinPkg/VbtBin cannot be used with the VBT binary provided.
Uploaded BSF only works for version 236, whereas provided VBT is 244.
When using the provided BSF to configure the VBT from MR5 FSP, VBT get corrupted as data are offset (can be verified very easily in the LFP Configuration, where the Panel Names are gibberish).

EDIT: Not OK for Version 236 or MR4 FSP either. Issue is less obvious but Panel Info are incorrect too. It looks like the BSF is from an even older version. For now, I added some skip lines in the BSF to correct the offset and modify the section I wanted, but having the correct BSF would be ideal.

Kind regards

**Comment by swong23** [comment]
Thanks, @belotv  for reporting this (with suggested skip lines/offset correction workaround).
The json file was up-streamed, it replaced the BSF file with newer (DisCon) tool to be used.
