### ISSUE TITLE
Tiger Lake IOT FSP files contain "Intel Confidential" in license headers

### ISSUE THREAD

**Issue by felixsinger** [intel/FSP#92]
Some of the Tiger Lake IOT FSP files contain "Intel Confidential" in their license headers.

https://github.com/intel/FSP/blob/master/TigerLakeFspBinPkg/TGL_IOT/TigerLakeFspPcds.dsc
https://github.com/intel/FSP/blob/master/TigerLakeFspBinPkg/TGL_IOT/TigerLakeFspBinPkg.dec
https://github.com/intel/FSP/blob/master/TigerLakeFspBinPkg/TGL_IOT/Include/GpioConfig.h
https://github.com/intel/FSP/blob/master/TigerLakeFspBinPkg/TGL_IOT/Include/FusaInfoHob.h

**Comment by swong23** [comment]
This issue has been resolved. The affected files has been replaced with the public facing version.
