### ISSUE TITLE
Alder Lake N is missing FirmwareVersionInfoHob.h

### ISSUE THREAD

**Issue by felixsinger** [intel/FSP#94]
Sorry that I didn't notice in #93. However, please upload that as well :)

**Comment by felixsinger** [comment]
@swong23 could you have a look?

**Comment by swong23** [comment]
Uploaded.

**Comment by felixsinger** [comment]
Thanks a lot!

**Comment by paulmenzel** [comment]
@swong23, it’d be great if you follow common software development best practices and reference the commit for example. (And commits should also have a commit message.)
