### ISSUE TITLE
Raptor Lake Refresh-S (LGA 1700) FSP support

### ISSUE THREAD

**Issue by zirblazer** [intel/FSP#96]
14th gen Core for desktops was released today. It is pretty much known than it is a simple rebranding since all the new parts are based on the same 13th gen Raptor Lake-S dies plus most likely 12th gen Alder Lake-S filling the lower end models like it happened for the 13th generation. This in theory should mean than the already available FSP for Raptor Lake-S should work with Raptor Lake Refresh-S since from the documentation standpoint they are treated as the same thing (As example, the old 13th Generation Intel Core Processors Datasheet was updated today and rebranded as 13th Generation Intel Core and Intel Core 14th Generation Processors Datasheet).
Can someone confirm whenever the already available FSP is intended to work for 14th gen Processors and if there is any other requeriment like minimum Microcode or ME version?

**Comment by nate-desimone** [comment]
RaptorLakeFspBinPkg has been released started with `2b0aac4`.

Raptor Lake requires a 16.1.xx.xxxx release of the ME firmware, whereas Alder Lake originally shipped with 16.0.xx.xxxx ME firmware. Raptor Lake has different CPUIDs and therefore different microcode.
